Add 3-rd task solution
elizabethfeden/qt-materials pull request #6
Opened 2022-03-05 08:04 UTC by DudkoAndrei

2022-03-05 15:52 UTC, elizabethfeden requested changes
Сделайте, чтобы компилилось :)

2022-03-05 15:52 UTC, elizabethfeden commented on sem-2/task-3/main.cpp
> +
Закройте скобку, а то не компилится :)

2022-03-05 15:52 UTC, elizabethfeden commented on sem-2/task-3/main_window.cpp
> +    layout_->addWidget(buttons_[i], i, 1, kSize, 2);
Не совсем правильное использование метода, 3 и 4 аргументы задают число клеток, которое должен занимать виджет, например, в сетке 3x3 в результате `addWidget(button, 0, 1, 2, 1)` `button` будет занимать две клетки с координатами (0, 1) и (1, 1). Здесь вы явно хотите просто размеры колонок поменять, для этого используется `layout->setColumnStretch`

2022-03-05 16:23 UTC, DudkoAndrei commented on sem-2/task-3/main.cpp
> +
[Fixed](https://github.com/elizabethfeden/qt-materials/pull/6/commits/0851c67f048a4807182a922675c28bf3dc78a87a)

2022-03-05 16:24 UTC, DudkoAndrei commented on sem-2/task-3/main_window.cpp
> +    layout_->addWidget(buttons_[i], i, 1, kSize, 2);
[Changed](https://github.com/elizabethfeden/qt-materials/pull/6/commits/75887907e413fc9330ea2258bee9288b7b14078e)

2022-03-06 15:50 UTC, elizabethfeden approved these changes

2022-03-06 15:50 UTC, merged